  function Levels() {
  }

  Levels.getAll = function() {
   
    return [{ distance: 500,
              obstacles: [
                { distance: 10, type: 'enemy', entity: new BadGuy() },
                { distance: 10, type: 'enemy', entity: new BadGuy('badGuyShip2') },
                { distance: 10, type: 'enemy', entity: new BadGuy('badGuyShip3') },
                { distance: 10, type: 'enemy', entity: new BadGuy('badGuyShip4') },
                { distance: 20, type: 'enemy', entity: new BadGuy() },
                { distance: 28, type: 'enemy', entity: new BadGuy() },
                { distance: 30, type: 'enemy', entity: new BadGuy() },
                { distance: 35, type: 'enemy', entity: new BadGuy() },
                { distance: 35, type: 'enemy', entity: new BadGuy() },
                { distance: 40, type: 'enemy', entity: new BadGuy() },
                { distance: 50, type: 'enemy', entity: new BadGuy() },
                { distance: 60, type: 'enemy', entity: new BadGuy() },
                { distance: 70, type: 'enemy', entity: new BadGuy() },
                { distance: 80, type: 'enemy', entity: new BadGuy() },
                { distance: 85, type: 'enemy', entity: new BadGuy() },
                { distance: 85, type: 'enemy', entity: new BadGuy() },
                { distance: 87, type: 'enemy', entity: new BadGuy() },
                { distance: 90, type: 'enemy', entity: new BadGuy() },
                { distance: 95, type: 'enemy', entity: new BadGuy() },
                { distance: 105, type: 'enemy', entity: new BadGuy() },
                { distance: 110, type: 'enemy', entity: new BadGuy() },
                { distance: 110, type: 'enemy', entity: new BadGuy() },
                { distance: 115, type: 'enemy', entity: new BadGuy() },
                { distance: 120, type: 'enemy', entity: new BadGuy() }, 
                { distance: 128, type: 'enemy', entity: new BadGuy() },
                { distance: 130, type: 'enemy', entity: new BadGuy() },
                { distance: 135, type: 'enemy', entity: new BadGuy() },
                { distance: 135, type: 'enemy', entity: new BadGuy() },
                { distance: 140, type: 'enemy', entity: new BadGuy() },
                { distance: 150, type: 'enemy', entity: new BadGuy() },
                { distance: 160, type: 'enemy', entity: new BadGuy() },
                { distance: 170, type: 'enemy', entity: new BadGuy() },
                { distance: 180, type: 'enemy', entity: new BadGuy() },
                { distance: 185, type: 'enemy', entity: new BadGuy() },
                { distance: 185, type: 'enemy', entity: new BadGuy() },
                { distance: 187, type: 'enemy', entity: new BadGuy() },
                { distance: 190, type: 'enemy', entity: new BadGuy() },
                { distance: 195, type: 'enemy', entity: new BadGuy() },
                { distance: 205, type: 'enemy', entity: new BadGuy() },
                { distance: 210, type: 'enemy', entity: new BadGuy() },
                { distance: 210, type: 'enemy', entity: new BadGuy() },
                { distance: 215, type: 'enemy', entity: new BadGuy() },
                { distance: 220, type: 'enemy', entity: new BadGuy() }, 
                { distance: 240, type: 'enemy', entity: new BadGuy() },
                { distance: 245, type: 'enemy', entity: new BadGuy() },
                { distance: 248, type: 'enemy', entity: new BadGuy() },
                { distance: 250, type: 'enemy', entity: new BadGuy() },
                { distance: 270, type: 'enemy', entity: new BadGuy() },
                { distance: 280, type: 'enemy', entity: new BadGuy() },
                { distance: 285, type: 'enemy', entity: new BadGuy() },
                { distance: 285, type: 'enemy', entity: new BadGuy() },
                { distance: 300, type: 'enemy', entity: new BadGuy() },
                { distance: 300, type: 'enemy', entity: new BadGuy() },
                { distance: 310, type: 'enemy', entity: new BadGuy() },
                { distance: 310, type: 'enemy', entity: new BadGuy() },
                { distance: 310, type: 'enemy', entity: new BadGuy() },
                { distance: 310, type: 'enemy', entity: new BadGuy() },
                { distance: 320, type: 'enemy', entity: new BadGuy() },
                { distance: 328, type: 'enemy', entity: new BadGuy() },
                { distance: 330, type: 'enemy', entity: new BadGuy() },
                { distance: 335, type: 'enemy', entity: new BadGuy() },
                { distance: 335, type: 'enemy', entity: new BadGuy() },
                { distance: 340, type: 'enemy', entity: new BadGuy() },
                { distance: 350, type: 'enemy', entity: new BadGuy() },
                { distance: 360, type: 'enemy', entity: new BadGuy() },
                { distance: 370, type: 'enemy', entity: new BadGuy() },
                { distance: 380, type: 'enemy', entity: new BadGuy() },
                { distance: 385, type: 'enemy', entity: new BadGuy() },
                { distance: 385, type: 'enemy', entity: new BadGuy() },
                { distance: 387, type: 'enemy', entity: new BadGuy() },
                { distance: 390, type: 'enemy', entity: new BadGuy() },
                { distance: 395, type: 'enemy', entity: new BadGuy() },
                { distance: 405, type: 'enemy', entity: new BadGuy() },
                { distance: 410, type: 'enemy', entity: new BadGuy() },
                { distance: 410, type: 'enemy', entity: new BadGuy() },
                { distance: 415, type: 'enemy', entity: new BadGuy() },
                { distance: 420, type: 'enemy', entity: new BadGuy('badGuyShip4') },              
                { distance: 440, type: 'enemy', entity: new BadGuy('badGuyShip4') },
                { distance: 445, type: 'enemy', entity: new BadGuy('badGuyShip4') },
                { distance: 448, type: 'enemy', entity: new BadGuy('badGuyShip4') },
                { distance: 450, type: 'enemy', entity: new BadGuy('badGuyShip4') },
                { distance: 470, type: 'enemy', entity: new BadGuy('badGuyShip4') },
                { distance: 480, type: 'enemy', entity: new BadGuy('badGuyShip4') },
                { distance: 490, type: 'enemy', entity: new BadGuy('boss1', 347, 278, 30, true) }
              ]
            }];
  }
